### ISSUE TITLE
Docker image got deleted

### ISSUE THREAD

**Issue by fschutt** [japaric/steed#152]
```
Unable to find image 'japaric/x86_64-unknown-linux-steed:v0.1.11' locally
Pulling repository docker.io/japaric/x86_64-unknown-linux-steed
docker: Tag v0.1.11 not found in repository docker.io/japaric/x86_64-unknown-linux-steed.
See 'docker run --help'.
```

Soo.. yeah. I'm not familiar with docker, seems like the documentation in the README is either out of date, the image got deleted or moved ...

**Comment by eguven** [comment]
looks like latest available is currently `v0.1.10`
https://hub.docker.com/r/japaric/x86_64-unknown-linux-steed/tags/
