### ISSUE TITLE
What is the current status of this repository now?

### ISSUE THREAD

**Issue by zhangpf** [japaric/steed#161]
This goal of the project is to build a standard library which is free of C. And I think it's really an attractive ambition. But I found the code has not been updated for nearly a year now (Sep 25th, 2018). Also, the build instruction in README seems to be also out-of-date.

1.  So are there any further plan on this project?
2.  Any obstacle has the development encountered to make any progress?
3.  Or any change on the rust language/dependent libraries themselves has to be settled?

@japaric

Thanks!

**Comment by japaric** [comment]
https://github.com/japaric/steed#status
