### ISSUE TITLE
minimal `test` crate

### ISSUE THREAD

**Issue by japaric** [japaric/steed#23]
- `term`
  - [ ] `collections::HashMap`
  - [ ] `env`
  - [ ] `io::BufReader`
  - [ ] `fs::metadata`
- `getopts`
  - [ ] ???
- `test`
  - [ ] ???

---

Let's make sure the `test` crate can be compiled against `steed` then we'll be able to use `#[test]` with `steed`.

It's OK to heavily modify the source as long as the main functionality remains. It's OK to drop parallelism and stub the `catch_unwind` calls (let panic!s kill the test runner)

**Comment by japaric** [comment]
To those interested in working on this.

Here's how to compile the `test` crate against `steed`:

```
# install Xargo HEAD
$ cargo install --git https://github.com/japaric/xargo

# get a STABLE libtest source
$ rustup default stable

$ rustup component add rust-src

$ cp -r $(rustc --print sysroot)/lib/rustlib/src/rust/src/lib{getopts,term,test} .

# now build `test` against `steed` using nightly
$ rustup default nightly

$ cd libtest

$ edit Xargo.toml && cat $_
```

``` toml
[dependencies.collections]

[dependencies.std]
git = "https://github.com/japaric/steed"  # `path` works too
stage = 1
```

```
$ edit Cargo.toml && tail -n5 $_
```

``` toml
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
```

```
$ xargo build --target x86_64-unknown-linux-gnu
```

It will obviously not compile! What has to be done next is:

- Port more of `std` API to `steed`, and

- Trim down `test`'s usage of `std`'s API. Dropping multithreading and unwinding
  is OK. Perhaps even drop CLI parsing and pretty printing from the test runner.

such that `test` is able to compile against `steed`. Then we'll be able to use
`#[test]` with `steed`!

You don't have to do everything yourself! Just listing what parts of `std`'s API
need to be ported to `steed` to complete this would be a great start, then we
can divide up the job of porting what's missing.

**Comment by japaric** [comment]
Errors from compiling the `term` crate:

```
error[E0432]: unresolved import `std::collections::HashMap`
error[E0432]: unresolved import `std::env`
error[E0432]: unresolved import `std::io::BufReader`
error[E0425]: cannot find function `metadata` in module `fs`
```

**Comment by tbu-** [comment]
@japaric Wrong thread?

**Comment by japaric** [comment]
@tbu- Ah, no. This is the right place. The `test` crate depends on the `term` and `getopts` crates so they must compile against `steed` too.

**Comment by tbu-** [comment]
Shimming `env::home_dir`, `env::var` and `env::var_os` for `libterm` and removing the `extern crate` definitions for `libc` and `panic_unwind`, the following errors are produced for `libtest` (duplicates removed):

    error[E0432]: unresolved import `std::panic::catch_unwind`
    error[E0432]: unresolved import `std::panic::AssertUnwindSafe`
    error[E0432]: unresolved import `std::sync::mpsc::channel`
    error[E0432]: unresolved import `std::sync::mpsc::Sender`
    error[E0432]: unresolved import `std::sync::Mutex`
    error[E0432]: unresolved import `std::thread`
    error[E0432]: unresolved import `std::sync::mpsc::RecvTimeoutError`
    error[E0425]: cannot find function `args` in module `env`
    error[E0425]: cannot find function `set_print` in module `io`
    error[E0425]: cannot find function `set_panic` in module `io`
    error: no method named `is_nan` found for type `f64` in the current scope
    error: no method named `abs` found for type `f64` in the current scope
    error: no method named `min` found for type `f64` in the current scope
    error: no method named `max` found for type `f64` in the current scope
    error: no method named `sqrt` found for type `f64` in the current scope
    error: no method named `floor` found for type `f64` in the current scope

For the `thread` module: `thread::Builder(..).name(..).spawn(..)`.

**Comment by briansmith** [comment]
> and stub the catch_unwind calls (let panic!s kill the test runner)

This means `#[should_panic]` tests won't work correctly. I guess they should be skipped with a warning message output.
