### ISSUE TITLE
What's the strategy for copying files

### ISSUE THREAD

**Issue by tbu-** [japaric/steed#39]
Do we want them as a whole, and just provide the interfaces they call (like the `sys` module in the standard library)? Would be easier to update in this case.

Or do we want to modify them? This would likely lead to less boilerplate. :)

On a side note: Is there an IRC channel?

**Comment by japaric** [comment]
> Do we want them as a whole, and just provide the interfaces they call (like the sys module in the standard library)? Would be easier to update in this case.

This approach. Ideally, we should be able to just copy root modules wholesale (like time in #31) and then write the actual implementation for them in the `sys` module (see #37)

> On a side note: Is there an IRC channel?

Just created #rust-steed

**Comment by FenrirWolf** [comment]
I'm a bit confused at how closely we're looking to model the organization of the current standard library. For example, what should be done with code that calls into sys_common? Should we flatten that layer away for steed implementations?

**Comment by FenrirWolf** [comment]
It's also a bit confusing that there's both a `linux` module and `sys/linux`. When should one be preferred over the other?

**Comment by japaric** [comment]
> For example, what should be done with code that calls into sys_common? Should we flatten that layer away for steed implementations?

It's OK to either drop sys_common altogether or modify it heavily. Anything that's not sys or sys_common should be kept as close as the original `std`.

> It's also a bit confusing that there's both a linux module and sys/linux.

Ideally there should only exist sys/linux (ie both linux and sys/linux should be merged) but I don't think that's possible right now because of how the io module is written.

**Comment by tbu-** [comment]
I got my answer, so I'm gonna close this issue.
