### ISSUE TITLE
implement std::collections

### ISSUE THREAD

**Issue by japaric** [japaric/steed#5]
I think most of would be simply re-exporting the stuff from the collections crate (modulo collections::HashMap which is covered by #4)

**Comment by japaric** [comment]
HashMap and HashSet depend on thread_local!

Blocked by #30

**Comment by briansmith** [comment]
> HashMap and HashSet depend on thread_local!

HashMap and HashSet can (and, IMO, should) be implemented without thread_local! by reverting the last change that added that dependency back.

**Comment by tbu-** [comment]
What was that change, and why do you consider it bad?

It's probably easiest to stay in sync with mainline Rust.

**Comment by briansmith** [comment]
It was https://github.com/rust-lang/rust/pull/37470. You can read https://github.com/rust-lang/rust/issues/36481 and the other issues regarding this and arrive at your own conclusion regarding the merits and demerits.

If you revert that then you can see how you can easily replace `thread_local!` with `lazy_static!`. That might not be a big enough win to justify forking, if you're planning to have `thread_local!` soon. `lazy_static!` is easier to implement.

**Comment by tbu-** [comment]
Done by #86.
