### ISSUE TITLE
Other operating systems?

### ISSUE THREAD

**Issue by sebasgarcep** [japaric/steed#51]
Right now this project is only targeting for Linux support. What about Windows, FreeBSD or macOs?

**Comment by tbu-** [comment]
Most other operating systems (including Windows) do not provide a stable syscall interface. Not sure about macOS and FreeBSD.

**Comment by japaric** [comment]
It's a [non-goal](https://github.com/japaric/steed#non-goals) to support other OSes at this time. Check that link and [this comment](https://users.rust-lang.org/t/lets-build-a-standard-library-std-free-of-c-code-dependencies-for-linux/8930/12?u=japaric) for rationale.
