### ISSUE TITLE
complete the I/O traits (Read, Write, BufRead)

### ISSUE THREAD

**Issue by japaric** [japaric/steed#9]
They are still missing some methods like `read_to_end` and `flush`.

This is mostly copy pasting but it's going to require finishing io::Error first, so ...

Blocked by #6

**Comment by tbu-** [comment]
This is already complete since #47: [`Read` in `src/io/mod.rs`](https://github.com/japaric/steed/blob/acc06ba5adb45595bd6277bf18a8d2d69e6e116d/src/io/mod.rs#L23), [`Write` in `src/io/mod.rs`](https://github.com/japaric/steed/blob/acc06ba5adb45595bd6277bf18a8d2d69e6e116d/src/io/mod.rs#L113).

**Comment by japaric** [comment]
Let's reuse this issue to track `BufRead` since that is still missing

**Comment by tbu-** [comment]
`BufRead` was added in #76: [`BufRead` in `src/io/mod.rs`](https://github.com/japaric/steed/blob/5279c7c08de10471f712e31cb24d8f88a815510f/src/io/mod.rs#L183).

**Comment by japaric** [comment]
Thanks, @tbu-!
